name: lint and test

on:
  pull_request:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/check.yml'
      - 'data_process/**'
      - 'inference/**'
      - 'models/**'
      - 'training/**'
      - 'utils/**'
      - 'tests/**'
      - 'examples/**'
      - 'setup.py'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test
