name: Publish to PyPI and TestPyPI

on:
  release:
    types: [created]


jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test


  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: build wheel
        run: |
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/
      - name: publish to test pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
